export const REMOVE_TODOLIST = 'REMOVE-TODOLIST';
export const ADD_TODOLIST = 'ADD-TODOLIST';
export const CHANGE_TODOLIST_TITLE = 'CHANGE-TODOLIST-TITLE';
export const CHANGE_TODOLIST_FILTER = 'CHANGE-TODOLIST-FILTER';
export const CHANGE_TODOLIST_STATUS = 'CHANGE-TODOLIST-STATUS';
export const SET_TODOLISTS = 'SET-TODOLISTS';
